### ISSUE TITLE
Shouldn't Tensor, Matrix and Vector share more code?

### ISSUE THREAD

**Issue by felix91gr** [nifty-swift/Nifty#24]
When you see T, M and V, they appear to be almost the same thing, if you judge them by their properties:

```swift
@Tensor
    /// Number of elements in the tensor.
    public let count: Int

    /// Number of elements in each dimension of the tensor.
    public var size: [Int]

    /// Data contained in tensor in row-major order.
    public var data: [T]

    /// Optional name of tensor (e.g., for use in display).
    public var name: String?

    /// Determine whether to show name when displaying tensor.
    public var showName: Bool

    /// Formatter to be used in displaying tensor elements.
    public var format: NumberFormatter
@Matrix
    /// Number of elements in the matrix.
    public let count: Int

    /// Number of [rows, columns] in the matrix.
    public var size: [Int]
    public var rows: Int { return self.size[0] }
    public var columns: Int { return self.size[1] }

    /// Data contained in matrix in row-major order.
    public var data: [T]

    /// Optional name of matrix (e.g., for use in display).
    public var name: String?

    /// Determine whether to show name when displaying matrx.
    public var showName: Bool

    /// Formatter to be used in displaying matrix elements.
    public var format: NumberFormatter    

@Vector
    /// Number of elements in vector.
    public let count: Int

    /// Data contained in vector.
    public var data: [T]

    /// Optional name of vector for use in display
    public var name: String?

    /// Determine whether to show name when displaying matrx.
    public var showName: Bool

    /// Formatter to be used in displaying matrix elements.
    public var format: NumberFormatter
```

For better maintainability, shouldn't they share more code? By means of a protocol, for example. This would help with not only maintenance, it would also help with testing and functions by joining together test cases and functions that are basically the same across types (see the `mean` function for example).

Btw, I like this project because it actually works in Linux :smile: I wanna help with this in my spare time

**Comment by philipce** [comment]
I think you're absolutely right! These should totally be refactored to adopt a common protocol. Thoughts on a protocol name? Something like NDArray or NiftyArray? Not in love with either...

And I'm happy to have another person interested in the project! It's good to see more people using Swift in Linux. The project has kind of taken a back seat for me the last couple months but I'm stoked to get back on it.

**Comment by felix91gr** [comment]
:thinking:  The "correct" or "by definition" name would be _Tensor,_ right? Because `Matrix` and `Vector` are also `Tensors`. But that, I think, can't be. Even if we use **protocol extensions** to provide default implementations, I don't think it's possible to have `Tensor` be only a protocol and also use it as a **struct** for Tensor operations.

(I had to mention that idea to be at peace with myself) :smile: 

Now, leaving it aside... what about calling it `TensorProtocol`? Or `TensorBody`? Something that describes what's inside :)

**Comment by philipce** [comment]
Haha that is technically correct... Yeah, I actually like TensorProtocol.
That lines up nicely with the fact that Vector and Matrix are just
specializations...

**Comment by felix91gr** [comment]
Haha, nice! We're set then :)

Want me to start a branch and we go from there?
Or a fork, and you give me feedback as I go c:

**Comment by philipce** [comment]
Yeah, sounds good! I've been working on some stuff in a separate project that I need to clean up and integrate here (some pandas type stuff and the beginnings of an optimization toolbox), so that's my main goal now... but if I can be of assistance in any way let me know!

**Comment by felix91gr** [comment]
I can start working on this! (Finally)
The exam period ended and I went on a short trip to the US. 

Now I’m back!
There are two things I want to work on: the TensorProtocol and the property testing (to augment the current tests).

I think the protocol (and subsequent refactoring) should come first. Right? The tests I think, are easier. But the structs should be fully defined before we improve the tests. Otherwise we would possibly be writing them again 🤔

_Sidenote?:_ I haven’t yet learned what I wanted to learn about Tensors (I was too busy with the exams), so I’ll take it slowly as I learn more. Can I ask you about Tensors as I learn about them? (If you can’t, don’t worry. I have StackExchange as plan B 😊)

**Comment by felix91gr** [comment]
Closing this one, as #29 took its role :D
