### ISSUE TITLE
General Discussion

### ISSUE THREAD

**Issue by philipce** [nifty-swift/Nifty#27]
@felix91gr 

Glad to see you made it through exams and had some time to travel! 

Sorry I've been absent. I've been making some big life changes--moving house, jobs, and other great things. I'll be getting back to Nifty in the next week or two for real. Here are the things I'm planning to work on (in no particular order): 

- Evaluate and possibly adopt some of the things added in Swift 4. Things that come to mind as potentially sweet: one sided ranges, Codable (as you noted earlier), generic subscripts, package manager update, numeric protocol, etc... 
- Finish the functions slated for v1.0 release. I think these are mostly minor things left, like some LAPACK wrappers and linspace and such. This will also involve ensuring that each function has a complete implementation (e.g. works on matrix, tensor, and vector--which in many cases will leverage your work on the tensor protocol).
- Finish the basic Series implementation
- Figure out the best interface to the optimization module and clean it up (there's an optimizer called SOMA that I'm using for some stuff, so I need him. I pushed a bunch of genetic algorithm stuff that is mostly junk so I won't bother merging that in v1)
- Work on reading/writing matrices and variables to file. This ties into our previous discussion of codable and stuff. I'd also like to make a convenient interface for writing an entire environment to a file to make it easy to export/share variables and stuff (something like a .mat file in matlab). This probably won't be in v1.
- I'd like to put together and publish a docker image that makes Nifty dead simple to get going on
- Documentation -- I'd like to revisit the jazzy docs. See if they've fixed some of the bugs. If not, I may write some scripts to reformat our comments and stuff. Overall, this is just a fleshing out of the docs and clean up.
- Sample projects. There's a demo project that uses some of the stuff, but not in a really compelling way. What I think I'd like to do is leave the demo code as snippets in a README, but then get rid of the lame demo project and replace it with something small but meaningful--some kind of simple machine learning thing springs to mind 
- I'll continue to add dumb tests like I have been for the above. But once we get a better framework figured out I'd like to start making better tests.

When all that's done, I'd like to make a real v1.0 release (I know, I know, there's already a 1.0--I have to delete that and do like a 0.9 or something while we finish up) and then I'd like to solicit some support for the project--post to the swift-users list, on reddit, etc. But before that, I'd like to get it to a more consumable state, which I think is covered between what you've talked about and the stuff I just mentioned.

Anyway, happy coding! Anything I can do to help you, just ask! I'm by no means an expert on tensors and such but I'm happy to chat/skype/whatever and discuss whatever--this is a learning experience for me too!

**Comment by felix91gr** [comment]
I'm sorry I haven't replied. I've been out of the computer for most of the week, and writing long answers through my phone is really hard xD

Here I go, I hope the wait makes up for it with a decent response:

>  I've been making some big life changes--moving house, jobs, and other great things

Sounds good! I hope everything turns out **great** :)
Don't worry about the pace, we both have things that demand our attention ^^
I myself tend to work slowly but surely, so please be patient with me :pray: 

> Evaluate and possibly adopt some of the things added in Swift 4 (...) 

Yes! Many of the changes in Swift 4 come in really handy for Nifty :)

> Finish the basic Series implementation
> Figure out the best interface to the optimization module

Woah, Series as in, infinite sums? I haven't looked at that module yet! I'm really curious to see how it works. Is it intended for numerical calculation of series?

And there's an optimization module? **Nice**

> Work on reading/writing matrices and variables to file. (...) This probably won't be in v1.

I agree. It's handy to have, but that's better left for when the library is more mature, isn't it?

> I'd like to put together and publish a docker image that makes Nifty dead simple to get going on

I like how you think. That's ambitious but it'd sure be nice for many people in areas unrelated to Swift!

> Documentation -- I'd like to revisit the jazzy docs (...)

I've never used Jazzy... sounds nice :) I'm gonna check it out

> Sample projects. (...) some kind of simple machine learning thing springs to mind

Sure!
For maybe next year, or whenever we launch 1.0, I'm thinking of making some graphics programming demos. A raytracer would be awesome. That was what in the end got me into math libraries, actually :). 
Just a basic one would suffice to show off some of the Linear Algebra functionality.

> I'll continue to add dumb tests like I have been for the above. But once we get a better framework figured out I'd like to start making better tests.

Indeed. I also can't wait to make nice tests with `SwiftCheck`, but first I should finish working on the TensorProtocol. Otherwise we might end up doing the same job twice :laughing:

**Comment by felix91gr** [comment]
As for the TensorProtocol... I know it might be overkill, but I want to get real good at it before doing the refactoring. I'm learning from [this playlist](https://www.youtube.com/playlist?list=PLRlVmXqzHjUQARA37r4Qw3SHPqVXgqO6c) right now together with a friend of mine.

It's gonna take me some weeks to finish it I think.

How can I ask you questions about Tensors and related topics? I regularly use, in descending order:
* Telegram
* Whatsapp
* Twitter
* iMessage

Tell me if I can contact you through any of those ^^ if none work for you, then maybe we can chat from time to time through Skype or Hangouts :)

**Comment by philipce** [comment]
Yeah slow and steady wins the race right? I'm in no rush.

The Series stuff is not like a mathematical series, but like a time series.
So like a bunch of data with time stamps. It's meant to provide similar
function to the Pandas <http://pandas.pydata.org/>library from python. Like
slicing a series to get data between two times, or interpolating values,
etc. It's something I've been needing in another project so I'm developing
it here as the other project's needs dictate. (My use case is I've got a
bunch of sensor readings all coming in at different times and frequencies
and I need a way to aggregate and analyze them and easily get estimated
values of all sensors at the exact same time).

Same goes for the optimization module--it's not so much of a module yet as
it is a single algorithm i needed for an unrelated optimization problem
that I've kind of thrown a more generic interface around (and a half baked
genetic algorithm implementation I was playing around with on a toy
problem). But these things are generally useful so they seem like they
belong, though need some work to make general.

Dude! Graphics demos would be awesome! I don't know anything about that
field so I'd be really interested in learning from you when those come
together.

As to the TensorProtocol: I think you're right that that is overkill, but
if you're interested in it, more power to you! My use--and I think this is
typical (outside of more physics driven fields like CFD), at least from the
straw poll I took among some peers last night--of tensor type data structs
(e.g. nd arrays from numpy, tensors from tensor flow, or just multi
dimensional array from matlab) is really just as a collection of matrices.
So for example, in a computer vision task we may use a "Tensor" struct (aka
"NDArray" aka "multidimensional array") to represent an RGB image. If the
image was 100 pixels square, the image "Tensor" would be
3x100x100--basically just a map of pixel values in each color channel. I
will probably just operate on each channel (each 2D slice) separately,
perhaps combining channels at points, but likely not performing algebraic
operations on the 3D tensor as a whole. The playlist you reference looks
like a more rigorous mathematical treatment of tensors, developing a lot of
the algebra and such behind general tensor operations. Now, this may be
interesting to you so like I said more power to you. But I think a lot of
those things are often impractical in this context--linear algebra
operations on a matrix (a 2D tensor) are already relatively complex, moving
to a 3D tensor makes them infeasible (e.g. rank computation on a 3D tensor
is NP complete). All this is to say: by all means dig as deep as you want
(and I'm happy to help and discuss, though I'm no expert in this area), but
I think the first version of Nifty probably needs no more (at least not
much more) functionality in the tensor protocol than what is there already;
as a first step, the tensor protocol can be a refactor to just reduce code
repetition.

As far as communication, how do you feel about slack? That would make it
easy for future developers to come up to speed pretty quickly. I've created
a team: https://nifty-swift.slack.com/. Let me know if you're interested in
that and I can invite you (just need your email address).

**Comment by felix91gr** [comment]
Oh, Slack, yes! I forgot about Slack xD
I used it a couple years ago for a course, and I loved it! 

My mail is: felix91gr@gmail.com

**Comment by felix91gr** [comment]
### Re: (xD)

#### Series

I see! Neat, I've never used that kind of Series in programming. What are you making with those sensors? Some kind of Computer Vision system? :)

#### Optimization

Ohh, I get it. Cool :)
I haven't built anything like an optimization module, although I've studied and worked on Search problems (the A* and IDA* kind of problems), so maybe I can help you with that ^^

#### Graphics

Man, graphics is awesome :sparkles: . Specially Raytracers, I have a special place in my heart for them :)
I'd be glad to teach you and help you learn about it ^^

#### Tensors

I see, alrighty then. It sounds like it's much simpler than what I thought it could be. That's good; I don't want to screw up the refactoring.

Still, I think I'd like to write this up as a MD document. Nothing long; just an outline, to formalize what will be the changes in API and where will the code need to change. We would go like this:
* I write it
* With your feedback we go back and forth if there are changes to be made
* I implement the refactoring and test the branch
* I do bugfixing and testing until everything passes
* Branch gets merged :)

**Comment by philipce** [comment]
Closing this issue as we now have Slack for this purpose.
