### ISSUE TITLE
Use Float32, 64 and 80’s “ulp” Property for Comparison

### ISSUE THREAD

**Issue by felix91gr** [nifty-swift/Nifty#28]
In the “isEqual” function, tolerance is a parameter of the function. We can actually do better, using “ulp”.

They talked a bit about this in the [34th episode of Swift Unwrapped](https://spec.fm/podcasts/swift-unwrapped/91615). In the shownotes there are two articles written by Jesse Squires where he talks about this in more detail.

What “ulp” is, in a nutshell, is a floating point value that shows you the next representable number at that level of precision. This will allows us to fine-tune any check that looks for floating point equality — not only looking for exact word equality, but rather by looking +- ulp (or wider, as needed) around the numbers.

**Comment by philipce** [comment]
This is a good idea. Currently, we have the `isequal` method which does more or less this, but without using the new builtin `ulp`. It uses the `eps` value which is defined in the constants struct (see the file `Nifty.swift`) for single and double precision. It would be a good idea to use the builtin `ulp` instead. Should be a straightforward substitution in `isequal`

**Comment by felix91gr** [comment]
👍🏻👍🏻

I want to do some experiments with ulp to understand exactly how it behaves.
I’d also put some unit tests of the function, that show how it can be used and what kind of comparisons it allows to do.

Both things will take a lot of time in the worst case, and I’ll have very little in November. I’d prefer to implement this in December, but if you want to have it implemented now, you can take it :)

**Comment by philipce** [comment]
Nope, no rush! I don't think it will change the user facing behavior, not as far as I can see anyway. So take your time!

**Comment by philipce** [comment]
Migrated issue to pivotal tracker
