### ISSUE TITLE
Cap or Finish the Tensor Refactor for 1.0

### ISSUE THREAD

**Issue by felix91gr** [nifty-swift/Nifty#29]
To finish the idea we started on #24.

I tried to make that Refactor work, and I think it may be close to finished. Tha said, it has some weird behavior and introduces strange complexities with the Associated Types that come in the Tensor Protocol. 

Maybe the Generics on Swift aren’t ready for such a refactor to be worth its weight yet. Maybe this code duplication is better than pure DRY since it’s much easier to read and to predict its behavior.

I don’t know. We can always refactor it later, specially if we have good tests (which I’m formalizing in another issue).

What do you think?

**Comment by philipce** [comment]
Just to follow up, I'm putting together a really minimal refactor... basically it will just create the TensorProtocol which will have shared properties. The actual code will be somewhat replicated and tailored to each structure. We can put a pin in a more thorough refactor for now.

**Comment by felix91gr** [comment]
Sounds awesome :)
