### ISSUE TITLE
Enhance the Test Suite

### ISSUE THREAD

**Issue by felix91gr** [nifty-swift/Nifty#30]
Since Nifty deals with simple structs with many functions and properties, it’s close to being perfect for Property Testing.

This issue consists on enhancing some of the already-in-place coverage with Properties by using [SwiftCheck](https://github.com/typelift/SwiftCheck). This library allows us to express properties using First Order Logic, which is quite powerful.

**Comment by felix91gr** [comment]
#25: reference properties and previous deliberation

**Comment by philipce** [comment]
I really like this. So I'm guessing something like, in the test suite a `testPropertyFoo` function for each property? E.g. ensure `A' x A = I` for matrix inversion? Is that the idea?

**Comment by felix91gr** [comment]
Yep! 😊 Property Testing is really quite something.

Exploring the reach of #28 will be very important here. I’m hoping we manage to use `ulp` for testing properties such as associativity. Associativity is usually false in floating-point math because of approximation errors. But my guess is that that error is bounded, and such bounds can be checked instead of checking for exact equality. We’ll see :)

**Comment by philipce** [comment]
Migrated issue to pivotal tracker
