### ISSUE TITLE
Allow specifying matrix layout

### ISSUE THREAD

**Issue by philipce** [nifty-swift/Nifty#33]
It would be cool to allow specifying whether your matrix should be stored row major or column major order (right now we just do row major).

This could be useful for a number of reasons. Right now though, I'm thinking it would be cool to default to column-major order on xcode builds. The lapack interface in the Accelerate framework doesn't give an option to have row major, so we end up transposing before and after certain operations, which is wasteful. If it were column major by default, we'd only have to do the extra transposes if the user specifically requested row major.

**Comment by felix91gr** [comment]
Oh, this is a good idea!
This will also check that our tests and high level functions are layout-independent, as they should be, right?

I have two techical questions:
1) In Linux, the Lapack interface allows for column-major order operations?
2) If (1)’s answer is not, then we should... hmm, have some kind of way to...
    - ...compile with a special flag to choose row-major instead when needed, or
    - ...compile it conditionally for Linux and MacOS.
    - And have it as a property of the Matrix Type, s.t. for interoperability purposes, we have some way of exchanging Matrices between different OSes with different Matrix layouts.

**Comment by philipce** [comment]
Yeah, when built with Xcode, Nifty uses Accelerate (since it's already available, why make people install something else). Accelerate uses clapack as the lapack interface, which does not let you choose the order. When built with the swift package manager (on mac or linux), it uses the lapacke interface (which I think is better, and possibly the only option of the 2 on linux, cant remember) and does allow specifying order. So on SPM builds, whatever the user chooses is easily done. On xcode builds, depending on the user's choice, we can just pass column major stuff straight in, otherwise transpose, pass it in, then transpose again.

**Comment by philipce** [comment]
And that's a good point, I hadn't thought about this from the testing perspective, but it would be really good to make sure the layout isn't changing things

**Comment by philipce** [comment]
Migrated issue to pivotal tracker
