### ISSUE TITLE
Matrix slices as views

### ISSUE THREAD

**Issue by philipce** [nifty-swift/Nifty#34]
I think right now, slicing a Matrix returns a new Matrix containing the sliced elements. I think we want to return a view so that I can slice a Matrix, do the operation on the slice, and have that reflected in the original matrix (in the same way that numpy does).

**Comment by felix91gr** [comment]
Makes sense. It would be just like the [SubString](https://developer.apple.com/documentation/swift/substring) seen in StdLib. Sounds like a nice model, and since numpy does the same... then, why not? :)

**Comment by philipce** [comment]
Yeah I'm not sure how to make this work... Does this entail creating like a MatrixSlice class that just holds the underlying ArraySlice? I haven't really looked much at how to work with ArraySlice

**Comment by felix91gr** [comment]
Hmm, yeah, at a glance... classes seem to be the way to go. Since a slice would be a reference, reference-type semantics make sense.

**Comment by philipce** [comment]
Migrated issue to pivotal tracker
