### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by Batarian711** [nifty-swift/Nifty#39]
Hi. I am a graphic designer. I volunteer to design a logo for open source projects. I can design it for you to use it in the readme file. What dou you say?

**Comment by philipce** [comment]
@Batarian711 Hi! Sorry for the delay in responding, I've been traveling for work and haven't had time to get on much this last week. We'd love your help, if the offer still stands! I promise to be more responsive in the future!

**Comment by Batarian711** [comment]
Of course I am proud of helping you. Anything you want me to design? If you have an idea?

**Comment by philipce** [comment]
That would be awesome! I'm not sure, I had a few ideas for some stylized text. I'll find the drawings, probably tomorrow, and post them. And one of the other developers mentioned an idea, I'll get him to post some details as well. But I think we're really open to ideas!

We're just getting started with trying out an external project management tool that we think will work better for internal development. We'll go ahead and close the issue and pick it up here: https://www.pivotaltracker.com/story/show/159223070. Once you've visited it, I can mark you as a member so we can more easily upload images and files and such

**Comment by Batarian711** [comment]
Of course
